### ISSUE TITLE
-12880 Error

### ISSUE THREAD

**Issue by Kmagn13** [plexinc-plugins/NickJr.bundle#10]
Getting Error -12880
Will work from WEB but opens popup http://media.mtvnservices.com/player/loader

**Comment by sander1** [comment]
> Getting Error -12880

This is not a channel specific issue, but an iOS issue. Please check out and/or post in the Plex for iOS forums about this https://forums.plex.tv/index.php/forum/59-plex-for-ios/

> Will work from WEB but opens popup http://media.mtvnservices.com/player/loader

This sounds like Plex Media Server does not find a matching URL Service for the channel. Please restart PMS to see if this fixes the issue.

**Comment by Kmagn13** [comment]
Tried this and a fresh install. Only have the issue with this plugin all
others are working as normal

On Thursday, March 26, 2015, Sander Spies <notifications@github.com> wrote:

> Getting Error -12880
>
> This is not a channel specific issue, but an iOS issue. Please check out
> and/or post in the Plex for iOS forums about this
> https://forums.plex.tv/index.php/forum/59-plex-for-ios/
>
> Will work from WEB but opens popup
> http://media.mtvnservices.com/player/loader
>
> This sounds like Plex Media Server does not find a matching URL Service
> for the channel. Please restart PMS to see if this fixes the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plexinc-plugins/NickJr.bundle/issues/10#issuecomment-86598372>
> .
>


-- 
Thank You,
Kelly Magnuson
